[[36m2024-03-22 12:01:38,521[0m][[35mHYDRA[0m] Launching 1 jobs locally[0m
[[36m2024-03-22 12:01:38,521[0m][[35mHYDRA[0m] 	#0 : experiment=dg/wilds/camelyon17_erm +data/dg/wilds@data=camelyon17_oracle data.transform.is_training=True seed=123 name_logger=prova_configs_train_newconf_call trainer=ddp trainer.max_epochs=3 +trainer.fast_dev_run=False logger=wandb logger.wandb.group=test_wilds[0m
[[36m2024-03-22 12:01:38,524[0m][[35mHYDRA[0m] Launching 1 jobs locally[0m
[[36m2024-03-22 12:01:38,524[0m][[35mHYDRA[0m] 	#0 : experiment=dg/wilds/camelyon17_erm +data/dg/wilds@data=camelyon17_oracle data.transform.is_training=True seed=123 name_logger=prova_configs_train_newconf_call trainer=ddp trainer.max_epochs=3 +trainer.fast_dev_run=False logger=wandb logger.wandb.group=test_wilds[0m
[[36m2024-03-22 12:01:38,526[0m][[35mHYDRA[0m] Launching 1 jobs locally[0m
[[36m2024-03-22 12:01:38,526[0m][[35mHYDRA[0m] 	#0 : experiment=dg/wilds/camelyon17_erm +data/dg/wilds@data=camelyon17_oracle data.transform.is_training=True seed=123 name_logger=prova_configs_train_newconf_call trainer=ddp trainer.max_epochs=3 +trainer.fast_dev_run=False logger=wandb logger.wandb.group=test_wilds[0m
[[36m2024-03-22 12:01:38,533[0m][[35mHYDRA[0m] Launching 1 jobs locally[0m
[[36m2024-03-22 12:01:38,533[0m][[35mHYDRA[0m] 	#0 : experiment=dg/wilds/camelyon17_erm +data/dg/wilds@data=camelyon17_oracle data.transform.is_training=True seed=123 name_logger=prova_configs_train_newconf_call trainer=ddp trainer.max_epochs=3 +trainer.fast_dev_run=False logger=wandb logger.wandb.group=test_wilds[0m
[rank: 1] Global seed set to 123
[rank: 3] Global seed set to 123
[rank: 2] Global seed set to 123
[rank: 0] Global seed set to 123
[[36m2024-03-22 12:01:38,953[0m][[34m__main__[0m][[32mINFO[0m] - Instantiating datamodule <src.data.wilds_datamodules.WILDSDataModule>[0m
[[36m2024-03-22 12:01:39,076[0m][[34m__main__[0m][[32mINFO[0m] - Instantiating model <src.models.erm.ERM>[0m
Error executing job with overrides: ['experiment=dg/wilds/camelyon17_erm', '+data/dg/wilds@data=camelyon17_oracle', 'data.transform.is_training=True', 'seed=123', 'name_logger=prova_configs_train_newconf_call', 'trainer=ddp', 'trainer.max_epochs=3', '+trainer.fast_dev_run=False', 'logger=wandb', 'logger.wandb.group=test_wilds']
Error executing job with overrides: ['experiment=dg/wilds/camelyon17_erm', '+data/dg/wilds@data=camelyon17_oracle', 'data.transform.is_training=True', 'seed=123', 'name_logger=prova_configs_train_newconf_call', 'trainer=ddp', 'trainer.max_epochs=3', '+trainer.fast_dev_run=False', 'logger=wandb', 'logger.wandb.group=test_wilds']
Error executing job with overrides: ['experiment=dg/wilds/camelyon17_erm', '+data/dg/wilds@data=camelyon17_oracle', 'data.transform.is_training=True', 'seed=123', 'name_logger=prova_configs_train_newconf_call', 'trainer=ddp', 'trainer.max_epochs=3', '+trainer.fast_dev_run=False', 'logger=wandb', 'logger.wandb.group=test_wilds']
[[36m2024-03-22 12:01:39,085[0m][[34msrc.utils.utils[0m][[31mERROR[0m] - [0m
Traceback (most recent call last):
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.models' has no attribute 'erm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/cluster/apps/nss/gcc-8.2.0/python/3.9.9/x86_64/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/cluster/home/vjimenez/adv_pa_new/src/models/erm.py", line 8, in <module>
    class ERM(LightningModule):
  File "/cluster/home/vjimenez/adv_pa_new/src/models/erm.py", line 25, in ERM
    def _extract_batch(self, batch: Union[dict, tuple]):
NameError: name 'Union' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'src.models.erm.ERM':
NameError("name 'Union' is not defined")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/home/vjimenez/adv_pa_new/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/cluster/home/vjimenez/adv_pa_new/src/train.py", line 54, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/cluster/project/jbuhmann/posterior_agreement/.venvs/adv_pa/lib64/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.models.erm.ERM', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[[36m2024-03-22 12:01:39,122[0m][[34msrc.utils.utils[0m][[32mINFO[0m] - Output dir: /cluster/project/jbuhmann/posterior_agreement/adv_pa/logs/victor/dg_wilds/multiruns/2024-03-22_12-01-38/0[0m
Error executing job with overrides: ['experiment=dg/wilds/camelyon17_erm', '+data/dg/wilds@data=camelyon17_oracle', 'data.transform.is_training=True', 'seed=123', 'name_logger=prova_configs_train_newconf_call', 'trainer=ddp', 'trainer.max_epochs=3', '+trainer.fast_dev_run=False', 'logger=wandb', 'logger.wandb.group=test_wilds']
Error locating target 'src.models.erm.ERM', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error locating target 'src.models.erm.ERM', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error locating target 'src.models.erm.ERM', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error locating target 'src.models.erm.ERM', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
srun: error: eu-g3-044: tasks 0-3: Exited with exit code 1
